#ifndef DEF_THE_BASTION_OF_TWILIGHT_H
#define DEF_THE_BASTION_OF_TWILIGHT_H

enum Data
{
	DATA_WYRMBREAKER_EVENT,
	DATA_VALIONA_EVENT,
	DATA_THERALION_EVENT,
	DATA_FELUDIUS_EVENT,
	DATA_IGNACIOUS_EVENT,
	DATA_ARION_EVENT,
	DATA_TERRASTRA_EVENT,
	DATA_MONSTROSITY_EVENT,
	DATA_CHOGALL_EVENT,
	DATA_TEAM_IN_INSTANCE,
};

enum Data64
{
	DATA_WYRMBREAKER,
	DATA_VALIONA,
	DATA_THERALION,
	DATA_FELUDIUS,
	DATA_IGNACIOUS,
	DATA_ARION,
	DATA_TERRASTRA,
	DATA_MONSTROSITY,
	DATA_CHOGALL,
};

enum CreatureIds
{
	//Boss
	BOSS_WYRMBREAKER = 44600,
	BOSS_VALIONA = 45992,
	BOSS_THERALION = 45993,
	BOSS_FELUDIUS = 43687,
	BOSS_IGNACIOUS = 43686,
	BOSS_ARION = 43688,
	BOSS_TERRASTRA = 43689,
	BOSS_MONSTROSITY = 43735,
	BOSS_CHOGALL = 43324,

	// Other NPC's
	NPC_SLATE_DRAKE = 44652,
	NPC_NETHER_SCION = 44645,
	NPC_STORM_RIDER = 44650,
	NPC_TIME_WARDEN = 44797,
};
#endif